name: Publish

on:
  release:
    types: [published, created, edited]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Job info
        run: echo GITHUB_SHA=$GITHUB_SHA GITHUB_REF=$GITHUB_REF
